/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  entry: {};
  blog: {};
  'blog.home': {};
  'blog.articles': {};
  'blog.articles.show': { slug: string };
  'blog.archive': {};
  'blog.members': {};
  'blog.login': {};
}

export interface RouteParamsInput {
  entry: {};
  blog: {};
  'blog.home': {};
  'blog.articles': {};
  'blog.articles.show': { slug: string };
  'blog.archive': {};
  'blog.members': {};
  'blog.login': {};
}

export interface RouteSearch {
  entry: {};
  blog: {};
  'blog.home': { query?: string };
  'blog.articles': { query?: string };
  'blog.articles.show': { ref?: string; filters?: readonly string[] };
  'blog.archive': {};
  'blog.members': {};
  'blog.login': { redirect?: string };
}

export interface RouteSearchInput {
  entry: {};
  blog: {};
  'blog.home': { query?: string };
  'blog.articles': { query?: string };
  'blog.articles.show': { ref?: string; filters?: readonly string[] };
  'blog.archive': {};
  'blog.members': {};
  'blog.login': { redirect?: string };
}

export interface RouteHash {
  entry: never;
  blog: never;
  'blog.home': never;
  'blog.articles': never;
  'blog.articles.show': 'comments' | 'share' | undefined;
  'blog.archive': never;
  'blog.members': never;
  'blog.login': never;
}

export interface RouteMeta {
  entry: {};
  blog: { title?: string };
  'blog.home': { title?: string };
  'blog.articles': { title?: string };
  'blog.articles.show': { title?: string };
  'blog.archive': { title?: string };
  'blog.members': { title?: string; requiresAuth?: boolean };
  'blog.login': { title?: string };
}

export interface RoutePaths {
  entry: '/';
  blog: '/blog';
  'blog.home': '/blog';
  'blog.articles': '/blog/articles';
  'blog.articles.show': '/blog/articles/{slug:regex([a-z0-9-]+)}';
  'blog.archive': '/blog/archive';
  'blog.members': '/blog/members';
  'blog.login': '/blog/login';
}

export interface RouteOutletContext {
  entry: {};
  blog: {};
  'blog.home': {};
  'blog.articles': {};
  'blog.articles.show': {};
  'blog.archive': {};
  'blog.members': {};
  'blog.login': {};
}

export interface RouterContracts {
  params: RouteParams;
  paramsInput: RouteParamsInput;
  search: RouteSearch;
  searchInput: RouteSearchInput;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
