/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  entry: {};
  blog: {};
  'blog.home': {};
  'blog.articles': {};
  'blog.articles.show': { slug: string };
  'blog.archive': {};
  'blog.members': {};
  'blog.login': {};
}

export interface RouteSearch {
  entry: {};
  blog: {};
  'blog.home': { query?: string | readonly string[] };
  'blog.articles': { query?: string | readonly string[] };
  'blog.articles.show': { ref?: string | readonly string[]; filters?: string | readonly string[] };
  'blog.archive': {};
  'blog.members': {};
  'blog.login': { redirect?: string | readonly string[] };
}

export interface RouteHash {
  entry: never;
  blog: never;
  'blog.home': never;
  'blog.articles': never;
  'blog.articles.show': 'comments' | 'share';
  'blog.archive': never;
  'blog.members': never;
  'blog.login': never;
}

export interface RouteMeta {
  entry: {};
  blog: { title?: string };
  'blog.home': { title?: string };
  'blog.articles': { title?: string };
  'blog.articles.show': { title?: string };
  'blog.archive': { title?: string };
  'blog.members': { title?: string; requiresAuth?: boolean };
  'blog.login': { title?: string };
}

export interface RoutePaths {
  entry: '/';
  blog: '/blog';
  'blog.home': '/blog';
  'blog.articles': '/blog/articles';
  'blog.articles.show': '/blog/articles/{slug:regex([a-z0-9-]+)}';
  'blog.archive': '/blog/archive';
  'blog.members': '/blog/members';
  'blog.login': '/blog/login';
}

export interface RouteOutletContext {
  entry: {};
  blog: {};
  'blog.home': {};
  'blog.articles': {};
  'blog.articles.show': {};
  'blog.archive': {};
  'blog.members': {};
  'blog.login': {};
}

export const routeIds = ['entry', 'blog', 'blog.home', 'blog.articles', 'blog.articles.show', 'blog.archive', 'blog.members', 'blog.login'] as const;
export const routePaths = {
  entry: '/',
  blog: '/blog',
  'blog.home': '/blog',
  'blog.articles': '/blog/articles',
  'blog.articles.show': '/blog/articles/{slug:regex([a-z0-9-]+)}',
  'blog.archive': '/blog/archive',
  'blog.members': '/blog/members',
  'blog.login': '/blog/login',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
