/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  entry: {};
  dashboard: {};
  'dashboard.overview': {};
  'dashboard.activity': {};
  'dashboard.settings': {};
  'dashboard.fullscreen': {};
  'dashboard.sidebar.activity': {};
}

export interface RouteSearch {
  entry: {};
  dashboard: {};
  'dashboard.overview': {};
  'dashboard.activity': {};
  'dashboard.settings': {};
  'dashboard.fullscreen': {};
  'dashboard.sidebar.activity': {};
}

export interface RouteHash {
  entry: never;
  dashboard: never;
  'dashboard.overview': never;
  'dashboard.activity': never;
  'dashboard.settings': never;
  'dashboard.fullscreen': never;
  'dashboard.sidebar.activity': never;
}

export interface RouteMeta {
  entry: {};
  dashboard: { section?: string };
  'dashboard.overview': { title?: string };
  'dashboard.activity': { title?: string };
  'dashboard.settings': { title?: string };
  'dashboard.fullscreen': {};
  'dashboard.sidebar.activity': { title?: string };
}

export interface RoutePaths {
  entry: '/';
  dashboard: '/dashboard';
  'dashboard.overview': '/dashboard';
  'dashboard.activity': '/dashboard/activity';
  'dashboard.settings': '/dashboard/settings';
  'dashboard.fullscreen': '/dashboard/fullscreen';
  'dashboard.sidebar.activity': '/dashboard/activity';
}

export interface RouteOutletContext {
  entry: {};
  dashboard: {};
  'dashboard.overview': {};
  'dashboard.activity': {};
  'dashboard.settings': {};
  'dashboard.fullscreen': {};
  'dashboard.sidebar.activity': { user: string };
}

export const routeIds = [
  'entry',
  'dashboard',
  'dashboard.overview',
  'dashboard.activity',
  'dashboard.settings',
  'dashboard.fullscreen',
  'dashboard.sidebar.activity',
] as const;
export const routePaths = {
  entry: '/',
  dashboard: '/dashboard',
  'dashboard.overview': '/dashboard',
  'dashboard.activity': '/dashboard/activity',
  'dashboard.settings': '/dashboard/settings',
  'dashboard.fullscreen': '/dashboard/fullscreen',
  'dashboard.sidebar.activity': '/dashboard/activity',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}
/* eslint-enable */
