/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  root: {};
  home: {};
  'users.show': { id: number };
  products: {};
  blocked: {};
}

export interface RouteSearch {
  root: {};
  home: {};
  'users.show': { tab?: string };
  products: { tags?: readonly string[] };
  blocked: {};
}

export interface RouteHash {
  root: never;
  home: never;
  'users.show': 'profile' | 'settings' | 'security';
  products: never;
  blocked: never;
}

export interface RouteMeta {
  root: {};
  home: { title?: string };
  'users.show': { title?: string; requiresAuth?: boolean };
  products: { title?: string };
  blocked: { requiresAuth?: boolean };
}

export interface RoutePaths {
  root: '/';
  home: '/';
  'users.show': '/users/{id:int}';
  products: '/products';
  blocked: '/blocked';
}

export interface RouteOutletContext {
  root: {};
  home: {};
  'users.show': {};
  products: {};
  blocked: {};
}

export const routeIds = ['root', 'home', 'users.show', 'products', 'blocked'] as const;
export const routePaths = {
  root: '/',
  home: '/',
  'users.show': '/users/{id:int}',
  products: '/products',
  blocked: '/blocked',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
