/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  entry: {};
  gallery: {};
  'gallery.index': {};
  'photos.show': { id: string };
}

export interface RouteSearch {
  entry: {};
  gallery: {};
  'gallery.index': {};
  'photos.show': { source?: string };
}

export interface RouteHash {
  entry: never;
  gallery: never;
  'gallery.index': never;
  'photos.show': 'details' | 'comments';
}

export interface RouteMeta {
  entry: {};
  gallery: { title?: string };
  'gallery.index': { title?: string };
  'photos.show': { title?: string };
}

export interface RoutePaths {
  entry: '/';
  gallery: '/gallery';
  'gallery.index': '/gallery';
  'photos.show': '/photos/{id:int}';
}

export interface RouteOutletContext {
  entry: {};
  gallery: {};
  'gallery.index': {};
  'photos.show': {};
}

export const routeIds = ['entry', 'gallery', 'gallery.index', 'photos.show'] as const;
export const routePaths = {
  entry: '/',
  gallery: '/gallery',
  'gallery.index': '/gallery',
  'photos.show': '/photos/{id:int}',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
