/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  root: {};
  home: {};
  'users.show': { id: number };
  login: {};
  'private.dashboard': {};
  blog: {};
  'blog.index': {};
  'blog.posts.show': { slug: string };
  'root.sidebar.user': { id: number };
}

export interface RouteSearch {
  root: {};
  home: {};
  'users.show': { tab?: string; preview?: string };
  login: {};
  'private.dashboard': {};
  blog: {};
  'blog.index': {};
  'blog.posts.show': {};
  'root.sidebar.user': {};
}

export interface RouteHash {
  root: never;
  home: never;
  'users.show': 'profile' | 'settings';
  login: never;
  'private.dashboard': never;
  blog: never;
  'blog.index': never;
  'blog.posts.show': never;
  'root.sidebar.user': never;
}

export interface RouteMeta {
  root: {};
  home: { title?: string };
  'users.show': { title?: string; requiresAuth?: boolean };
  login: { title?: string };
  'private.dashboard': { title?: string; requiresAuth?: boolean };
  blog: {};
  'blog.index': { title?: string };
  'blog.posts.show': { title?: string };
  'root.sidebar.user': { title?: string };
}

export interface RoutePaths {
  root: '/';
  home: '/';
  'users.show': '/users/{id:int}';
  login: '/login';
  'private.dashboard': '/private';
  blog: '/blog';
  'blog.index': '/blog';
  'blog.posts.show': '/blog/{slug:regex([a-z0-9-]+)}';
  'root.sidebar.user': '/users/{id:int}';
}

export interface RouteOutletContext {
  root: {};
  home: {};
  'users.show': {};
  login: {};
  'private.dashboard': {};
  blog: {};
  'blog.index': {};
  'blog.posts.show': {};
  'root.sidebar.user': {};
}

export const routeIds = ['root', 'home', 'users.show', 'login', 'private.dashboard', 'blog', 'blog.index', 'blog.posts.show', 'root.sidebar.user'] as const;
export const routePaths = {
  root: '/',
  home: '/',
  'users.show': '/users/{id:int}',
  login: '/login',
  'private.dashboard': '/private',
  blog: '/blog',
  'blog.index': '/blog',
  'blog.posts.show': '/blog/{slug:regex([a-z0-9-]+)}',
  'root.sidebar.user': '/users/{id:int}',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
