/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  root: {};
  'root.sidebar.user': {
    id: string;
  };
  home: {};
  'users.show': {
    id: string;
  };
  login: {};
  'private.dashboard': {};
  blog: {};
  'blog.index': {};
  'blog.posts.show': {
    slug: string;
  };
}

export interface RouteSearch {
  root: {};
  'root.sidebar.user': {};
  home: {};
  'users.show': {
    tab?: string;
    preview?: boolean;
  };
  login: {};
  'private.dashboard': {};
  blog: {};
  'blog.index': {};
  'blog.posts.show': {};
}

export interface RouteHash {
  root: never;
  'root.sidebar.user': never;
  home: never;
  'users.show': 'profile' | 'settings';
  login: never;
  'private.dashboard': never;
  blog: never;
  'blog.index': never;
  'blog.posts.show': never;
}

export interface RouteMeta {
  root: {};
  'root.sidebar.user': {
    title?: string;
  };
  home: {
    title?: string;
  };
  'users.show': {
    title?: string;
    requiresAuth?: boolean;
  };
  login: {
    title?: string;
  };
  'private.dashboard': {
    title?: string;
    requiresAuth?: boolean;
  };
  blog: {};
  'blog.index': {
    title?: string;
  };
  'blog.posts.show': {
    title?: string;
  };
}

export interface RoutePaths {
  root: '/';
  'root.sidebar.user': '/users/{id:int}';
  home: '/';
  'users.show': '/users/{id:int}';
  login: '/login';
  'private.dashboard': '/private';
  blog: '/blog';
  'blog.index': '/blog';
  'blog.posts.show': '/blog/{slug:regex([a-z0-9-]+)}';
}

export interface RouteOutletContext {
  root: {};
  'root.sidebar.user': {
    source: 'root-sidebar';
  };
  home: {};
  'users.show': {};
  login: {};
  'private.dashboard': {};
  blog: {};
  'blog.index': {};
  'blog.posts.show': {
    source: 'blog-modal';
  };
}

export const routeIds = ['root', 'root.sidebar.user', 'home', 'users.show', 'login', 'private.dashboard', 'blog', 'blog.index', 'blog.posts.show'] as const;
export const routePaths = {
  root: '/',
  'root.sidebar.user': '/users/{id:int}',
  home: '/',
  'users.show': '/users/{id:int}',
  login: '/login',
  'private.dashboard': '/private',
  blog: '/blog',
  'blog.index': '/blog',
  'blog.posts.show': '/blog/{slug:regex([a-z0-9-]+)}',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}
/* eslint-enable */
