/* This file is generated by @cookbook/router-cli. Do not edit directly. */
import type { RouterContracts } from './contracts';

declare module '@cookbook/router' {
  interface Register {
    contracts: RouterContracts;
  }
}

export {};
