/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  entry: {};
  login: {};
  create: {};
  overview: {};
  users: {};
  'users.index': {};
  'users.details': { slug: string };
  reports: {};
  'broken-page': {};
  'not-found': {};
}

export interface RouteSearch {
  entry: {};
  login: { redirect?: string | readonly string[] };
  create: {};
  overview: { page?: string | readonly string[]; pageSize?: string | readonly string[]; visitors?: string | readonly string[] };
  users: {};
  'users.index': {};
  'users.details': {};
  reports: {};
  'broken-page': {};
  'not-found': {};
}

export interface RouteHash {
  entry: never;
  login: never;
  create: never;
  overview: never;
  users: never;
  'users.index': never;
  'users.details': never;
  reports: never;
  'broken-page': never;
  'not-found': never;
}

export interface RouteMeta {
  entry: {};
  login: { access?: string };
  create: {};
  overview: {};
  users: {};
  'users.index': {};
  'users.details': {};
  reports: {};
  'broken-page': {};
  'not-found': { access?: string };
}

export interface RoutePaths {
  entry: '/';
  login: '/login';
  create: '/create';
  overview: '/overview';
  users: '/users';
  'users.index': '/users';
  'users.details': '/users/{slug:slug}';
  reports: '/reports';
  'broken-page': '/broken-page';
  'not-found': '/not-found';
}

export interface RouteOutletContext {
  entry: {};
  login: {};
  create: {};
  overview: {};
  users: {};
  'users.index': {};
  'users.details': {};
  reports: {};
  'broken-page': {};
  'not-found': {};
}

export const routeIds = ['entry', 'login', 'create', 'overview', 'users', 'users.index', 'users.details', 'reports', 'broken-page', 'not-found'] as const;
export const routePaths = {
  entry: '/',
  login: '/login',
  create: '/create',
  overview: '/overview',
  users: '/users',
  'users.index': '/users',
  'users.details': '/users/{slug:slug}',
  reports: '/reports',
  'broken-page': '/broken-page',
  'not-found': '/not-found',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
