/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

export interface RouteParams {
  entry: {};
  'entry.redirect': {};
  create: {};
  'new-message': {};
  overview: {};
  users: {};
  'users.index': {};
  'users.details': { slug: string };
  documents: {};
  'documents.index': {};
  'documents.details': { documentId: string };
  reports: {};
  'broken-page': {};
  policies: {};
  'terms-of-service': {};
  'privacy-policy': {};
  login: {};
  'not-found': { path: string };
}

export interface RouteSearch {
  entry: {};
  'entry.redirect': {};
  create: {};
  'new-message': {};
  overview: { page?: string | readonly string[]; pageSize?: string | readonly string[]; visitors?: string | readonly string[] };
  users: {};
  'users.index': { page?: string | readonly string[]; pageSize?: string | readonly string[]; status?: string | readonly string[]; role?: string | readonly string[]; q?: string | readonly string[] };
  'users.details': {};
  documents: {};
  'documents.index': {};
  'documents.details': {};
  reports: {};
  'broken-page': {};
  policies: {};
  'terms-of-service': {};
  'privacy-policy': {};
  login: { redirect?: string | readonly string[] };
  'not-found': {};
}

export interface RouteHash {
  entry: never;
  'entry.redirect': never;
  create: never;
  'new-message': never;
  overview: never;
  users: never;
  'users.index': never;
  'users.details': never;
  documents: never;
  'documents.index': never;
  'documents.details': never;
  reports: never;
  'broken-page': never;
  policies: never;
  'terms-of-service': never;
  'privacy-policy': never;
  login: never;
  'not-found': never;
}

export interface RouteMeta {
  entry: {};
  'entry.redirect': {};
  create: {};
  'new-message': {};
  overview: {};
  users: {};
  'users.index': {};
  'users.details': {};
  documents: {};
  'documents.index': {};
  'documents.details': {};
  reports: {};
  'broken-page': {};
  policies: { access?: string };
  'terms-of-service': { access?: string };
  'privacy-policy': { access?: string };
  login: { access?: string };
  'not-found': { access?: string };
}

export interface RoutePaths {
  entry: '/';
  'entry.redirect': '/';
  create: '/create';
  'new-message': '/messages/new';
  overview: '/overview';
  users: '/users';
  'users.index': '/users';
  'users.details': '/users/{slug:slug}';
  documents: '/documents';
  'documents.index': '/documents';
  'documents.details': '/documents/{documentId:slug}';
  reports: '/reports';
  'broken-page': '/broken-page';
  policies: '/policies';
  'terms-of-service': '/policies/terms-of-service';
  'privacy-policy': '/policies/privacy-policy';
  login: '/login';
  'not-found': '/{*path}';
}

export interface RouteOutletContext {
  entry: {};
  'entry.redirect': {};
  create: {};
  'new-message': {};
  overview: {};
  users: {};
  'users.index': {};
  'users.details': {};
  documents: {};
  'documents.index': {};
  'documents.details': {};
  reports: {};
  'broken-page': {};
  policies: {};
  'terms-of-service': {};
  'privacy-policy': {};
  login: {};
  'not-found': {};
}

export const routeIds = ['entry', 'entry.redirect', 'create', 'new-message', 'overview', 'users', 'users.index', 'users.details', 'documents', 'documents.index', 'documents.details', 'reports', 'broken-page', 'policies', 'terms-of-service', 'privacy-policy', 'login', 'not-found'] as const;
export const routePaths = {
  entry: '/',
  'entry.redirect': '/',
  create: '/create',
  'new-message': '/messages/new',
  overview: '/overview',
  users: '/users',
  'users.index': '/users',
  'users.details': '/users/{slug:slug}',
  documents: '/documents',
  'documents.index': '/documents',
  'documents.details': '/documents/{documentId:slug}',
  reports: '/reports',
  'broken-page': '/broken-page',
  policies: '/policies',
  'terms-of-service': '/policies/terms-of-service',
  'privacy-policy': '/policies/privacy-policy',
  login: '/login',
  'not-found': '/{*path}',
} as const;

export interface RouterContracts {
  params: RouteParams;
  search: RouteSearch;
  hash: RouteHash;
  meta: RouteMeta;
  paths: RoutePaths;
  outletContext: RouteOutletContext;
}

/* eslint-enable */
