/* eslint-disable */
/* This file is generated by @cookbook/router-cli. Do not edit directly. */

import { defineRouteTree } from '@cookbook/router/route-config';
import type { RouteDefinition, RouteModulePreload } from '@cookbook/router/route-config';

import { brokenPageRoute as brokenPageRoute0 } from '../app/pages/broken-page/broken-page.route';
import { createRoute as createRoute1 } from '../app/pages/create/create.route';
import { documentDetailsRoute as documentDetailsRoute2 } from '../app/pages/documents/details/document-details.route';
import { documentsRoute as documentsRoute3 } from '../app/pages/documents/documents.route';
import { loginRoute as loginRoute4 } from '../app/pages/login/login.route';
import { entryRoute as entryRoute5 } from '../app/pages/main.route';
import { newMessageRoute as newMessageRoute6 } from '../app/pages/messages/new/new-message.route';
import { notFoundRoute as notFoundRoute7 } from '../app/pages/not-found/not-found.route';
import { overviewRoute as overviewRoute8 } from '../app/pages/overview/overview.route';
import { policiesRoute as policiesRoute9 } from '../app/pages/policies/policies.route';
import { privacyPolicyRoute as privacyPolicyRoute10 } from '../app/pages/policies/privacy-policy/privacy-policy.route';
import { termsOfServiceRoute as termsOfServiceRoute11 } from '../app/pages/policies/terms-of-service/terms-of-service.route';
import { reportsRoute as reportsRoute12 } from '../app/pages/reports/reports.route';
import { userDetailsRoute as userDetailsRoute13 } from '../app/pages/users/details/user-details.route';
import { usersRoute as usersRoute14 } from '../app/pages/users/users.route';
import { pathConstraints as __cookbookPathConstraints } from '../app/lib/routes/path-constraints';

function __cookbookWithModulePreload<Route extends RouteDefinition>(
  route: Route,
  modulePreload: RouteModulePreload,
): Route {
  return { ...route, modulePreload };
}

function __cookbookWithModulePreloads<Routes extends readonly RouteDefinition[]>(
  routes: Routes,
  modulePreload: RouteModulePreload,
): Routes {
  return routes.map((route) => __cookbookWithModulePreload(route, modulePreload)) as unknown as Routes;
}

export const routes = defineRouteTree({
  routes: [
    __cookbookWithModulePreload(brokenPageRoute0, () => import('../app/pages/broken-page/broken-page.route').then(() => undefined)),
    __cookbookWithModulePreload(createRoute1, () => import('../app/pages/create/create.route').then(() => undefined)),
    __cookbookWithModulePreload(documentDetailsRoute2, () => import('../app/pages/documents/details/document-details.route').then(() => undefined)),
    __cookbookWithModulePreload(documentsRoute3, () => import('../app/pages/documents/documents.route').then(() => undefined)),
    __cookbookWithModulePreload(loginRoute4, () => import('../app/pages/login/login.route').then(() => undefined)),
    __cookbookWithModulePreload(entryRoute5, () => import('../app/pages/main.route').then(() => undefined)),
    __cookbookWithModulePreload(newMessageRoute6, () => import('../app/pages/messages/new/new-message.route').then(() => undefined)),
    __cookbookWithModulePreload(notFoundRoute7, () => import('../app/pages/not-found/not-found.route').then(() => undefined)),
    __cookbookWithModulePreload(overviewRoute8, () => import('../app/pages/overview/overview.route').then(() => undefined)),
    __cookbookWithModulePreload(policiesRoute9, () => import('../app/pages/policies/policies.route').then(() => undefined)),
    __cookbookWithModulePreload(privacyPolicyRoute10, () => import('../app/pages/policies/privacy-policy/privacy-policy.route').then(() => undefined)),
    __cookbookWithModulePreload(termsOfServiceRoute11, () => import('../app/pages/policies/terms-of-service/terms-of-service.route').then(() => undefined)),
    __cookbookWithModulePreload(reportsRoute12, () => import('../app/pages/reports/reports.route').then(() => undefined)),
    __cookbookWithModulePreload(userDetailsRoute13, () => import('../app/pages/users/details/user-details.route').then(() => undefined)),
    __cookbookWithModulePreload(usersRoute14, () => import('../app/pages/users/users.route').then(() => undefined)),
  ],
  pathConstraints: __cookbookPathConstraints,
} as const);

/* eslint-enable */
