import { dirname, relative, sep } from 'node:path';
import type { DefineRoutesOptions, RouteDefinition } from '@cookbook/router';
import type {
  CliRouteSource,
  GeneratedRouteTreeRuntimeOptions,
  RouteFileExport,
} from '../contracts';
import { quote } from './render-types';

interface ImportBinding {
  readonly sourcePath: string;
  readonly exportName: string;
  readonly localName: string;
  readonly kind: RouteFileExport['kind'];
}

interface RuntimeImportBinding {
  readonly sourcePath: string;
  readonly exportName: string;
  readonly localName: string;
}

/** Renders `.cookbook-router/routes.ts` from loaded route-source exports. */
export function generateRoutesModule(
  sources: readonly CliRouteSource[],
  routesPath = '.cookbook-router/routes.ts',
  options: DefineRoutesOptions = {},
  runtimeOptions: GeneratedRouteTreeRuntimeOptions = {},
): string {
  const imports = collectImportBindings(sources);
  const runtimeImports = collectRuntimeImports(runtimeOptions);

  if (!imports[0]) {
    return [
      '/* eslint-disable */',
      '/* This file is generated by @cookbook/router-cli. Do not edit directly. */',
      '',
      'export const routes = [] as const;',
      '',
      '/* eslint-enable */',
      '',
    ].join('\n');
  }

  const staticReExport = getSingleStaticRoutesReExport(sources, imports, options, runtimeImports);

  if (staticReExport !== undefined) {
    return renderStaticRoutesReExport(staticReExport, routesPath);
  }

  assertSourcePathConstraintsArePreserved(sources);

  const hasRouteDeclarations = imports.some(isRouteDeclarationBinding);

  return [
    '/* eslint-disable */',
    '/* This file is generated by @cookbook/router-cli. Do not edit directly. */',
    '',
    hasRouteDeclarations
      ? "import { defineRouteTree } from '@cookbook/router';"
      : "import { defineRoutes } from '@cookbook/router';",
    "import type { RouteDefinition, RouteModulePreload } from '@cookbook/router';",
    '',
    ...imports.map((binding) => renderImport(binding, routesPath)),
    ...runtimeImports.map((binding) => renderRuntimeImport(binding, routesPath)),
    '',
    ...renderModulePreloadHelpers(),
    ...(hasRouteDeclarations
      ? renderDefineRouteTreeExport(imports, options, runtimeImports, routesPath)
      : renderDefineRoutesExport(imports, options, runtimeImports, routesPath)),
    '',
    '/* eslint-enable */',
    '',
  ].join('\n');
}

function renderModulePreloadHelpers(): readonly string[] {
  return [
    'function __cookbookWithModulePreload<Route extends RouteDefinition>(',
    '  route: Route,',
    '  modulePreload: RouteModulePreload,',
    '): Route {',
    '  return { ...route, modulePreload };',
    '}',
    '',
    'function __cookbookWithModulePreloads<Routes extends readonly RouteDefinition[]>(',
    '  routes: Routes,',
    '  modulePreload: RouteModulePreload,',
    '): Routes {',
    '  return routes.map((route) => __cookbookWithModulePreload(route, modulePreload)) as unknown as Routes;',
    '}',
    '',
  ];
}

function renderModulePreload(binding: ImportBinding, routesPath: string): string {
  const importPath = toImportSpecifier(dirname(routesPath), binding.sourcePath);
  return `() => import(${quote(importPath)}).then(() => undefined)`;
}

function getSingleStaticRoutesReExport(
  sources: readonly CliRouteSource[],
  imports: readonly ImportBinding[],
  options: DefineRoutesOptions,
  runtimeImports: readonly RuntimeImportBinding[],
): ImportBinding | undefined {
  if (imports.length !== 1 || isRouteDeclarationBinding(imports[0]) || runtimeImports[0]) {
    return undefined;
  }

  const source = sources.length === 1 ? sources[0] : undefined;
  const binding = imports[0];

  if (
    source === undefined ||
    binding === undefined ||
    source.routeExports?.length !== 1 ||
    binding.kind !== 'routes'
  ) {
    return undefined;
  }

  if (!sameRouteOptions(source.routeOptions, options)) {
    return undefined;
  }

  if (hasNestedAbsoluteChildPath(source.routes)) {
    return undefined;
  }

  return binding;
}

function sameRouteOptions(
  left: DefineRoutesOptions | undefined,
  right: DefineRoutesOptions | undefined,
): boolean {
  return (
    samePathOptions(left?.pathOptions, right?.pathOptions) &&
    sameConstraintNames(left?.pathConstraints, right?.pathConstraints)
  );
}

function samePathOptions(
  left: DefineRoutesOptions['pathOptions'],
  right: DefineRoutesOptions['pathOptions'],
): boolean {
  return JSON.stringify(left ?? {}) === JSON.stringify(right ?? {});
}

function sameConstraintNames(
  left: DefineRoutesOptions['pathConstraints'],
  right: DefineRoutesOptions['pathConstraints'],
): boolean {
  const leftNames = Object.keys(left ?? {}).sort();
  const rightNames = Object.keys(right ?? {}).sort();
  return JSON.stringify(leftNames) === JSON.stringify(rightNames);
}

function hasNestedAbsoluteChildPath(routes: readonly RouteDefinition[], isNested = false): boolean {
  for (const route of routes) {
    if (isNested && typeof route.path === 'string' && route.path.startsWith('/')) {
      return true;
    }

    if (route.children && hasNestedAbsoluteChildPath(route.children, true)) {
      return true;
    }
  }

  return false;
}

function renderStaticRoutesReExport(binding: ImportBinding, routesPath: string): string {
  return [
    '/* eslint-disable */',
    '/* This file is generated by @cookbook/router-cli. Do not edit directly. */',
    '',
    renderImport({ ...binding, localName: 'routes' }, routesPath),
    '',
    'export { routes };',
    '',
    '/* eslint-enable */',
    '',
  ].join('\n');
}

function assertSourcePathConstraintsArePreserved(sources: readonly CliRouteSource[]): void {
  const constrainedSources = sources.filter(
    (source) => Object.keys(source.routeOptions?.pathConstraints ?? {})[0],
  );

  if (!constrainedSources[0]) {
    return;
  }

  throw new Error(
    [
      'Generated routes.ts cannot safely preserve pathConstraints declared inside multiple or rewrapped route source files.',
      'Move custom pathConstraints to cookbook-router.config.ts as a named import from a runtime-safe module,',
      'or generate from a single static route-tree source so the original defineRoutes()/defineRouteTree() export can be re-exported directly.',
    ].join(' '),
  );
}

function renderDefineRouteTreeExport(
  imports: readonly ImportBinding[],
  options: DefineRoutesOptions,
  runtimeImports: readonly RuntimeImportBinding[],
  routesPath: string,
): readonly string[] {
  return [
    'export const routes = defineRouteTree({',
    '  routes: [',
    ...imports.map((binding) =>
      isRouteArrayBinding(binding)
        ? `    ...__cookbookWithModulePreloads(${binding.localName}, ${renderModulePreload(binding, routesPath)}),`
        : `    __cookbookWithModulePreload(${binding.localName}, ${renderModulePreload(binding, routesPath)}),`,
    ),
    '  ],',
    ...renderDefineRouteTreeOptions(options, runtimeImports),
    '} as const);',
  ];
}

function renderDefineRoutesExport(
  imports: readonly ImportBinding[],
  options: DefineRoutesOptions,
  runtimeImports: readonly RuntimeImportBinding[],
  routesPath: string,
): readonly string[] {
  const optionLines = renderDefineRoutesOptions(options, runtimeImports);

  return [
    'export const routes = defineRoutes([',
    ...imports.map(
      (binding) =>
        `  ...__cookbookWithModulePreloads(${binding.localName}, ${renderModulePreload(binding, routesPath)}),`,
    ),
    optionLines[0] ? '] as const, {' : '] as const);',
    ...optionLines,
    ...(optionLines[0] ? ['});'] : []),
  ];
}

function collectRuntimeImports(
  options: GeneratedRouteTreeRuntimeOptions,
): readonly RuntimeImportBinding[] {
  const imports: RuntimeImportBinding[] = [];

  if (options.pathConstraints !== undefined) {
    imports.push({
      sourcePath: options.pathConstraints.path,
      exportName: options.pathConstraints.exportName,
      localName: '__cookbookPathConstraints',
    });
  }

  return imports;
}

function collectImportBindings(sources: readonly CliRouteSource[]): readonly ImportBinding[] {
  const imports: ImportBinding[] = [];
  let index = 0;

  for (const source of sources) {
    for (const routeExport of source.routeExports ?? []) {
      imports.push({
        sourcePath: source.path,
        exportName: routeExport.exportName,
        localName: `${routeExport.exportName}${index}`,
        kind: routeExport.kind,
      });
      index += 1;
    }
  }

  return imports;
}

function isRouteDeclarationBinding(binding: ImportBinding | undefined): boolean {
  return binding?.kind === 'route';
}

function isRouteArrayBinding(binding: ImportBinding): boolean {
  return binding.kind === 'routes' || binding.kind === 'routeTree';
}

function renderImport(binding: ImportBinding, routesPath: string): string {
  const importPath = toImportSpecifier(dirname(routesPath), binding.sourcePath);
  return `import { ${binding.exportName} as ${binding.localName} } from ${quote(importPath)};`;
}

function renderRuntimeImport(binding: RuntimeImportBinding, routesPath: string): string {
  const importPath = toImportSpecifier(dirname(routesPath), binding.sourcePath);
  return `import { ${binding.exportName} as ${binding.localName} } from ${quote(importPath)};`;
}

function toImportSpecifier(fromDir: string, targetPath: string): string {
  let specifier = relative(fromDir || '.', targetPath)
    .split(sep)
    .join('/');

  if (!specifier.startsWith('.')) {
    specifier = `./${specifier}`;
  }

  return stripKnownExtension(specifier);
}

function stripKnownExtension(specifier: string): string {
  return specifier.replace(/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/, '');
}

function renderDefineRouteTreeOptions(
  options: DefineRoutesOptions,
  runtimeImports: readonly RuntimeImportBinding[],
): readonly string[] {
  return renderRouteOptionLines(options, runtimeImports, '  ');
}

function renderDefineRoutesOptions(
  options: DefineRoutesOptions,
  runtimeImports: readonly RuntimeImportBinding[],
): readonly string[] {
  return renderRouteOptionLines(options, runtimeImports, '  ');
}

function renderRouteOptionLines(
  options: DefineRoutesOptions,
  runtimeImports: readonly RuntimeImportBinding[],
  indent: string,
): readonly string[] {
  const lines: string[] = [];

  if (options.pathOptions !== undefined) {
    lines.push(`${indent}pathOptions: ${JSON.stringify(options.pathOptions)},`);
  }

  const pathConstraints = runtimeImports.find(
    (binding) => binding.localName === '__cookbookPathConstraints',
  );

  if (pathConstraints !== undefined) {
    lines.push(`${indent}pathConstraints: ${pathConstraints.localName},`);
  }

  return lines;
}
