import { normalizeRoutes, validateRoutes } from '@cookbook/router';
import type {
  NormalizedRoute,
  NormalizedRouteSlotConfig,
  RouteDefinition,
  RouteParamDefinition,
} from '@cookbook/router';

interface GeneratedRouteContract {
  readonly id: string;
  readonly params: string;
  readonly search: string;
  readonly hash: string;
  readonly meta: string;
  readonly path: string;
}

export function generateContracts(routes: readonly RouteDefinition[]): string {
  validateRoutes(routes);
  const normalized = flattenNormalizedRoutes(normalizeRoutes(routes));
  const contracts = normalized.map(toGeneratedRouteContract);

  return [
    '/* eslint-disable */',
    '/* This file is generated by @cookbook/router-cli. Do not edit directly. */',
    '',
    renderInterface(
      'RouteParams',
      contracts.map((contract) => [contract.id, contract.params]),
    ),
    '',
    renderInterface(
      'RouteSearch',
      contracts.map((contract) => [contract.id, contract.search]),
    ),
    '',
    renderInterface(
      'RouteHash',
      contracts.map((contract) => [contract.id, contract.hash]),
    ),
    '',
    renderInterface(
      'RouteMeta',
      contracts.map((contract) => [contract.id, contract.meta]),
    ),
    '',
    renderInterface(
      'RoutePaths',
      contracts.map((contract) => [contract.id, contract.path]),
    ),
    '',
    renderInterface(
      'RouteOutletContext',
      contracts.map((contract) => [contract.id, '{}']),
    ),
    '',
    'export const routeIds = [' +
      contracts.map((contract) => quote(contract.id)).join(', ') +
      '] as const;',
    'export const routePaths = {' +
      contracts.map((contract) => `\n  ${quoteProperty(contract.id)}: ${contract.path},`).join('') +
      '\n} as const;',
    '',
    'export interface RouterContracts {',
    '  params: RouteParams;',
    '  search: RouteSearch;',
    '  hash: RouteHash;',
    '  meta: RouteMeta;',
    '  paths: RoutePaths;',
    '  outletContext: RouteOutletContext;',
    '}',
    '',
    '/* eslint-enable */',
    '',
  ].join('\n');
}

function toGeneratedRouteContract(route: NormalizedRoute): GeneratedRouteContract {
  return {
    id: route.id,
    params: renderParams(route.params),
    search: renderSearch(route.route.search),
    hash: renderHash(route.route.hash),
    meta: renderMeta(route.route.meta),
    path: route.fullPath === undefined ? 'never' : quote(route.fullPath),
  };
}

function renderInterface(name: string, entries: readonly (readonly [string, string])[]): string {
  const lines = [`export interface ${name} {`];

  for (const [id, value] of entries) {
    lines.push(`  ${quoteProperty(id)}: ${value};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function renderParams(params: readonly RouteParamDefinition[]): string {
  const entries = params.map((param) => `${quoteProperty(param.name)}: string`);
  return renderObject(entries);
}

function renderSearch(search: RouteDefinition['search']): string {
  if (!search) {
    return '{}';
  }

  const entries = Object.entries(search).map(
    ([key, value]) => `${quoteProperty(key)}?: ${renderSearchValue(value)}`,
  );

  return renderObject(entries);
}

function renderSearchValue(_value: unknown): string {
  return 'string';
}

function renderHash(hash: RouteDefinition['hash']): string {
  if (!hash) {
    return 'never';
  }

  return hash[0] ? hash.map(quote).join(' | ') : 'never';
}

function renderMeta(meta: RouteDefinition['meta']): string {
  if (!meta) {
    return '{}';
  }

  const entries = Object.entries(meta).map(
    ([key, value]) => `${quoteProperty(key)}?: ${typeof value}`,
  );
  return renderObject(entries);
}

function renderObject(entries: readonly string[]): string {
  return entries[0] ? `{ ${entries.join('; ')} }` : '{}';
}

function quote(value: string): string {
  const escaped = value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
  return `'${escaped}'`;
}

function quoteProperty(value: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : quote(value);
}

function flattenNormalizedRoutes(routes: readonly NormalizedRoute[]): readonly NormalizedRoute[] {
  const flattened: NormalizedRoute[] = [];
  const stack = [...routes].reverse();

  while (stack.length) {
    const route = stack.pop();

    if (!route) {
      continue;
    }

    flattened.push(route);

    const slots = Object.values(route.layout?.slots ?? {}) as readonly NormalizedRouteSlotConfig[];

    for (let index = slots.length - 1; index >= 0; index--) {
      const slot = slots[index];

      if (!slot) {
        continue;
      }

      for (let routeIndex = slot.routes.length - 1; routeIndex >= 0; routeIndex--) {
        const slotRoute = slot.routes[routeIndex];

        if (slotRoute) {
          stack.push(slotRoute);
        }
      }
    }

    for (let index = route.children.length - 1; index >= 0; index--) {
      const child = route.children[index];

      if (child) {
        stack.push(child);
      }
    }
  }

  return flattened;
}
