import { normalizeRoutes, registerUrlPathConstraints, validateRoutes } from '@cookbook/router';
import type {
  DefineRoutesOptions,
  NormalizedRoute,
  RouteDefinition,
  RouterPathOptions,
} from '@cookbook/router';
import { flattenNormalizedRoutes } from './flatten-normalized-routes';
import { renderRouteHash } from './generate-route-hash';
import { renderRouteParams } from './generate-route-params';
import { renderRouteSearch } from './generate-route-search';
import { quote, quoteProperty, renderInterface, renderObject } from './render-types';

interface GeneratedRouteContract {
  readonly id: string;
  readonly params: string;
  readonly search: string;
  readonly hash: string;
  readonly meta: string;
  readonly path: string;
}

/**
 * Generates the TypeScript route contract file from normalized routes.
 *
 * The generated output includes params, search, hash, meta, paths, outlet
 * context, route ids, and route paths. Custom path constraints supplied through
 * `defineRoutes` options are registered with URLKit before validation so the
 * generated params/search/hash state follows URLKit parsing semantics.
 */
export function generateContracts(
  routes: readonly RouteDefinition[],
  options: DefineRoutesOptions | RouterPathOptions = {},
): string {
  const pathOptions = resolveGenerationPathOptions(options);
  validateRoutes(routes, pathOptions);
  const normalized = flattenNormalizedRoutes(normalizeRoutes(routes, pathOptions));
  const contracts = normalized.map(toGeneratedRouteContract);

  return [
    '/* eslint-disable */',
    '/* This file is generated by @cookbook/router-cli. Do not edit directly. */',
    '',
    renderInterface(
      'RouteParams',
      contracts.map((contract) => [contract.id, contract.params]),
    ),
    '',
    renderInterface(
      'RouteSearch',
      contracts.map((contract) => [contract.id, contract.search]),
    ),
    '',
    renderInterface(
      'RouteHash',
      contracts.map((contract) => [contract.id, contract.hash]),
    ),
    '',
    renderInterface(
      'RouteMeta',
      contracts.map((contract) => [contract.id, contract.meta]),
    ),
    '',
    renderInterface(
      'RoutePaths',
      contracts.map((contract) => [contract.id, contract.path]),
    ),
    '',
    renderInterface(
      'RouteOutletContext',
      contracts.map((contract) => [contract.id, '{}']),
    ),
    '',
    'export const routeIds = [' +
      contracts.map((contract) => quote(contract.id)).join(', ') +
      '] as const;',
    'export const routePaths = {' +
      contracts.map((contract) => `\n  ${quoteProperty(contract.id)}: ${contract.path},`).join('') +
      '\n} as const;',
    '',
    'export interface RouterContracts {',
    '  params: RouteParams;',
    '  search: RouteSearch;',
    '  hash: RouteHash;',
    '  meta: RouteMeta;',
    '  paths: RoutePaths;',
    '  outletContext: RouteOutletContext;',
    '}',
    '',
    '/* eslint-enable */',
    '',
  ].join('\n');
}

function toGeneratedRouteContract(route: NormalizedRoute): GeneratedRouteContract {
  return {
    id: route.id,
    params: renderRouteParams(route.params),
    search: renderRouteSearch(route.route.search),
    hash: renderRouteHash(route.route.hash),
    meta: renderMeta(route.route.meta),
    path: route.fullPath === undefined ? 'never' : quote(route.fullPath),
  };
}

function renderMeta(meta: RouteDefinition['meta']): string {
  if (!meta) {
    return '{}';
  }

  const entries = Object.entries(meta).map(
    ([key, value]) => `${quoteProperty(key)}?: ${typeof value}`,
  );
  return renderObject(entries);
}

function resolveGenerationPathOptions(
  options: DefineRoutesOptions | RouterPathOptions,
): RouterPathOptions {
  if (isDefineRoutesOptions(options)) {
    registerUrlPathConstraints(options.pathConstraints);
    return options.pathOptions ?? {};
  }

  registerUrlPathConstraints();
  return options;
}

function isDefineRoutesOptions(
  options: DefineRoutesOptions | RouterPathOptions,
): options is DefineRoutesOptions {
  return 'pathOptions' in options || 'pathConstraints' in options;
}
