/**
 * Generates the module augmentation file that registers generated contracts with
 * the core router package and the React adapter package.
 */
export function generateRegister(): string {
  return [
    '/* This file is generated by @cookbook/router-cli. Do not edit directly. */',
    "import type { RouterContracts } from './contracts';",
    '',
    "declare module '@cookbook/router' {",
    '  interface Register {',
    '    contracts: RouterContracts;',
    '  }',
    '}',
    '',
    "declare module '@cookbook/router-react' {",
    '  interface Register {',
    '    contracts: RouterContracts;',
    '  }',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
}
