import { describe, expect, it } from 'vitest';

describe('package entrypoint', () => {
  it('exports public router primitives and diagnostics', async () => {
    const module = await import('./index');

    expect(Object.keys(module).sort()).toEqual([
      'completeTransition',
      'createBrowserHistory',
      'createConstraint',
      'createGeneratedHrefMismatchError',
      'createHydrationMismatchError',
      'createInterceptHistoryState',
      'createInvalidParamError',
      'createMalformedRedirectError',
      'createMemoryHistory',
      'createMemoryRouter',
      'createMissingOutletContextError',
      'createMissingParamError',
      'createMissingPathError',
      'createMissingProviderError',
      'createRouteUrlContract',
      'createRouter',
      'createStaticHistory',
      'createStaticRouter',
      'createUnknownRouteError',
      'defineRoutes',
      'deserializeRouterState',
      'flattenRoutes',
      'getConstraint',
      'getResolvedSlot',
      'hasConstraint',
      'matchRoutes',
      'normalizeCallSiteIntercept',
      'normalizeConfiguredIntercepts',
      'normalizeRoutes',
      'parseHref',
      'rankRoutes',
      'registerPathConstraints',
      'registerUrlPathConstraints',
      'resolveIntercept',
      'resolveSlots',
      'resolveUrlOptions',
      'restoreInterceptFromState',
      'runAfterNavigate',
      'runBeforeNavigate',
      'runMiddleware',
      'runNavigationError',
      'runTransition',
      'serializeRouterState',
      'stringifyRouterState',
      'unregisterConstraint',
      'validateInterceptTargets',
      'validateRoutes',
    ]);
  });
});
